### ISSUE TITLE
RPM spec file for building on RHEL/CentOS

### ISSUE THREAD

**Issue by pdurbin** [ProvTools/prov-cpl#6]
As a sysadmin attempting to follow a future version of the Dataverse Installation Guide, I would like to install prov-cpl on RHEL/CentOS (the recommended distribution for Dataverse) as an RPM using yum rather than compiling it myself. The Dataverse Installation Guide already hosts an RPM for rapache at http://guides.dataverse.org/en/4.8.5/installation/r-rapache-tworavens.html#c-rapache (see https://github.com/IQSS/dataverse/issues/975 for initial work on this) so the idea is to do the same with prov-cpl, except that we'll be writing the RPM spec file ourselves rather than using one that has been provided by the author. Once we get the RPM spec file working, we'll make a pull request to add it to this prov-cpl repo unless there are any objections.

The good news is that yesterday I was able to get prov-cpl to build on Ubuntu 10.04 using a script I wrote at https://github.com/IQSS/dataverse/blob/84011328dc60f6fadc846a639fc26240cb55832b/doc/sphinx-guides/source/_static/developers/prov/install/vagrant.sh

The bad news is that the compiler on CentOS 7 is too old. Here's the output from `make install`:

```
[root@standalone prov-cpl]# make install
In file included from ../include/cplxx.h:50:0,
                 from cpl-private.h:38,
                 from cpl-standalone.cpp:36:
cpl-standalone/../include/json.hpp:67:10: error: #error "unsupported GCC version - see https://github.com/nlohmann/json#supported-compilers"
         #error "unsupported GCC version - see https://github.com/nlohmann/json#supported-compilers"
          ^
make[2]: *** [build/release/project.mk] Error 1
make[1]: *** [release] Error 2
make: *** [install] Error 1
[root@standalone prov-cpl]# cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 
[root@standalone prov-cpl]# 
[root@standalone prov-cpl]# g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)
```

https://github.com/nlohmann/json#supported-compilers indicates that "GCC 4.9 - 7.2 (and possibly later)" is supported. (Other compilers I haven't used much such as Clang are also listed.) According to the error above, CentOS 7 ships with GCC 4.8.5. How can I install a newer version of GCC on CentOS 7? Are there other ways to get prov-cpl to compile on RHEL/CentOS?

**Comment by jacksonokuhn** [comment]
https://gist.github.com/craigminihan/b23c06afd9073ec32e0c

**Comment by DirectXMan12** [comment]
SCL maybe?  Let me see what comes up...

**Comment by DirectXMan12** [comment]
yep, SCL: https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/

**Comment by DirectXMan12** [comment]
see also https://access.redhat.com/documentation/en-us/red_hat_developer_toolset/7/html/7.0_release_notes/dts7.0_release#changes-upgrades

**Comment by pdurbin** [comment]
@DirectXMan12 thanks! I got the initial `sudo make install` to work by installing a newer compiler as you suggested:

```
sudo yum install -y redhat-lsb-core centos-release-scl devtoolset-7 boost-devel unixODBC-devel
cd /home/vagrant/prov-cpl
scl enable devtoolset-7 bash
sudo make install
```

Next I need to start writing an RPM spec file.

**Comment by pdurbin** [comment]
When I run `sudo make install` the files are written here:

```
/usr/local/lib/libcpl-odbc.3.0.so
/usr/local/lib/libcpl-odbc.3.so
/usr/local/lib/libcpl-odbc.so
/usr/local/lib/libcpl.3.0.so
/usr/local/lib/libcpl.3.so
/usr/local/lib/libcpl.so
```

I guess at this point I'm wondering if there's an RPM spec file I could use as a template that writes our library files like this.

**Comment by DirectXMan12** [comment]
So, my recommendation for writing specfiles is to find something with similar steps in Fedora, and look at how that does it, but this page is also useful: https://fedoraproject.org/wiki/How_to_create_an_RPM_package.  Since you'd need to use SCL, you might need this page: https://www.softwarecollections.org/en/docs/guide/.  Haven't gotten a chance to fully read though it myself, though.

**Comment by pdurbin** [comment]
@DirectXMan12 thanks, I stubbed out a spec file at https://github.com/IQSS/dataverse/commit/2f131b6

To use SCL I'm sourcing the `enable` script like this:

```
%build
source /opt/rh/devtoolset-7/enable
%{__make}
```

Still a lot of work to do but it's a start. 😄

**Comment by DirectXMan12** [comment]
I'm not sure that's quite the right way to do it.  The SCL page I linked seems to indicate that there's a special spec file predicate that you use instead, like `%{?scl:Requires: %scl_runtime}`, but it's really hard to tell.  Might be worth looking at one of the packages in that software collection to see how it does it.
